apiVersion: apps/v1
kind: Deployment
metadata:
  name: fnal-rucio-daemons-reaper
spec:
  template:
    spec:
      initContainers:
      - name: grid-certs
        image: ghcr.io/fnal-fife/fetch-crl-cron:latest
        imagePullPolicy: Always
        volumeMounts:
        - name: ca-volume
          mountPath: /out/
        resources:
          requests:
            cpu: 500m
            memory: 600Mi
          limits:
            cpu: 500m
            memory: 600Mi
      volumes:
       - name: ca-volume
         secret:
           $patch: delete
         persistentVolumeClaim:
           claimName: grid-certificates-pvc
